version: 2
updates:
  - package-ecosystem: npm
    directory: /react-speech-app
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
